services:
  mc:
    image: itzg/minecraft-server:java21-alpine
    environment:
      EULA: "true"
      TYPE: "PAPER"
      PLUGINS: |
        https://download.geysermc.org/v2/projects/geyser/versions/2.6.0/builds/latest/downloads/spigot
        https://download.geysermc.org/v2/projects/floodgate/versions/2.2.3/builds/latest/downloads/spigot
    ports:
      - "25565:25565"
      - "19132:19132/udp"
    volumes:
      - store:/data

  dnsmasq:
    image: 4km3/dnsmasq:2.90-r3-alpine-latest
    networks:
      dns:
        ipv4_address: 192.168.86.100
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "mco.lbsg.net:192.168.86.100"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    cap_add:
      - NET_ADMIN

volumes:
  store:

networks:
  dns:
    driver: macvlan
    driver_opts:
      parent: enp4s0  # Replace eth0 with the correct network interface on your host
    ipam:
      config:
        - subnet: 192.168.86.0/24  # Replace with the subnet of your LAN
          gateway: 192.168.86.1
